2024-06-06 14:13:32,242 INFO    MainThread:124541 [wandb_setup.py:_flush():76] Current SDK version is 0.15.9
2024-06-06 14:13:32,243 INFO    MainThread:124541 [wandb_setup.py:_flush():76] Configure stats pid to 124541
2024-06-06 14:13:32,243 INFO    MainThread:124541 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2024-06-06 14:13:32,243 INFO    MainThread:124541 [wandb_setup.py:_flush():76] Loading settings from /mnt/ceph_rbd/synth-icl/wandb/settings
2024-06-06 14:13:32,243 WARNING MainThread:124541 [wandb_setup.py:_flush():76] Unknown environment variable: WANDB_SERVICE
2024-06-06 14:13:32,243 INFO    MainThread:124541 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'entity': 'edin', 'project': 'gmm-extrapolate', 'sweep_id': 'ywuls4pw', 'root_dir': '/mnt/ceph_rbd/synth-icl', 'run_id': '7mi5a3b4', 'sweep_param_path': '/mnt/ceph_rbd/synth-icl/wandb/sweep-ywuls4pw/config-7mi5a3b4.yaml'}
2024-06-06 14:13:32,243 INFO    MainThread:124541 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-06-06 14:13:32,243 INFO    MainThread:124541 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program': '/mnt/ceph_rbd/synth-icl/main.py'}
2024-06-06 14:13:32,243 INFO    MainThread:124541 [wandb_init.py:_log_setup():524] Logging user logs to /mnt/ceph_rbd/synth-icl/wandb/run-20240606_141332-7mi5a3b4/logs/debug.log
2024-06-06 14:13:32,243 INFO    MainThread:124541 [wandb_init.py:_log_setup():525] Logging internal logs to /mnt/ceph_rbd/synth-icl/wandb/run-20240606_141332-7mi5a3b4/logs/debug-internal.log
2024-06-06 14:13:32,243 INFO    MainThread:124541 [wandb_init.py:init():564] calling init triggers
2024-06-06 14:13:32,244 INFO    MainThread:124541 [wandb_init.py:init():571] wandb.init called with sweep_config: {'data': 'gauss-mix-model', 'data.dim': 16, 'data.num_classes': 2, 'data.num_xy_pairs_train': 32, 'data.num_xy_pairs_val': 1024, 'eval.every': 5000, 'eval.iters': 1000, 'model': 'mamba', 'model.d_model': 64, 'model.max_seq_len': 4096, 'model.n_layer': 12, 'optimizer': 'adamw', 'optimizer.betas': [0.9, 0.95], 'optimizer.lr': 0.001, 'optimizer.weight_decay': 0, 'scheduler.decay_lr': True, 'seed': 5947, 'train.batch_size': 128, 'train.do_early_stop': False, 'train.iters': 100001, 'train.log_every': 1000, 'train.parallel_loss': True}
config: {}
2024-06-06 14:13:32,244 INFO    MainThread:124541 [wandb_init.py:init():613] starting backend
2024-06-06 14:13:32,244 INFO    MainThread:124541 [wandb_init.py:init():617] setting up manager
2024-06-06 14:13:32,252 INFO    MainThread:124541 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-06-06 14:13:32,254 INFO    MainThread:124541 [wandb_init.py:init():623] backend started and connected
2024-06-06 14:13:32,272 INFO    MainThread:124541 [wandb_run.py:_config_callback():1282] config_cb None None {'data': 'gauss-mix-model', 'data.dim': 16, 'data.num_classes': 2, 'data.num_xy_pairs_train': 32, 'data.num_xy_pairs_val': 1024, 'eval.every': 5000, 'eval.iters': 1000, 'model': 'mamba', 'model.d_model': 64, 'model.max_seq_len': 4096, 'model.n_layer': 12, 'optimizer': 'adamw', 'optimizer.betas': [0.9, 0.95], 'optimizer.lr': 0.001, 'optimizer.weight_decay': 0, 'scheduler.decay_lr': True, 'seed': 5947, 'train.batch_size': 128, 'train.do_early_stop': False, 'train.iters': 100001, 'train.log_every': 1000, 'train.parallel_loss': True}
2024-06-06 14:13:32,274 INFO    MainThread:124541 [wandb_init.py:init():714] updated telemetry
2024-06-06 14:13:32,281 INFO    MainThread:124541 [wandb_init.py:init():747] communicating run to backend with 60.0 second timeout
2024-06-06 14:14:32,317 ERROR   MainThread:124541 [wandb_init.py:init():773] encountered error: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-06-06 14:14:32,409 ERROR   MainThread:124541 [wandb_init.py:init():1182] Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/root/anaconda3/envs/icl/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1164, in init
    run = wi.init()
  File "/root/anaconda3/envs/icl/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
